name: build

on:
  pull_request:
  push:
    paths:
    - *.json
    - src/*.ts

    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup node 20
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'npm'

      - run: |
          npm update
          npm ci
          npm build
      
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated dist/ update
          skip_fetch: true
          skip_checkout: true
