name: build

on:
  pull_request:
    paths:
    - "*.json"
    - "src/*.ts"
    - ".github/workflows/workflow.yml"

    branches:
      - "master"
      - "releases/*"
      
  push:
    paths:
    - "*.json"
    - "src/*.ts"
    - ".github/workflows/workflow.yml"

    branches:
      - "master"
      - "releases/*"
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup node 20
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'npm'

      - run: |
          npm update
          npm install
          npm run build
      
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated dist/ update
          skip_fetch: true
          skip_checkout: true
